In [ ]:

!pip install pandas
!pip install numpy
!pip install openpyxl

In [1]:
# Passo a Passo
# Passo 1: Importar a base de dados
# Passo 2: Visualizar a base de dados
# Passo 3: Corrigir as cagadas da base de dados
# Passo 4: Primeira analise do cancelamento dos clientes ( Qual a % de clientes que cancelou)
# Passo 5: Analise a causa do cancelamento dos clientes

In [15]:
# Passo 1:
import pandas as pd

tabela = pd.read_csv("cancelamentos_sample.csv")
tabela = tabela.drop(columns="CustomerID")

# Passo 2:
display(tabela)

# Passo 3: Corrigir as cagadas da base de dados
tabela = tabela.dropna()
display(tabela.info())

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [30]:
# Passo 4: Primeira analise do cancelamento dos clientes ( Qual a % de clientes que cancelou)



display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True))
# exibir em porcentagem ja : display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

cancelou
1.0    28394
0.0    21606
Name: count, dtype: int64

cancelou
1.0    56.8%
0.0    43.2%
Name: proportion, dtype: object

In [33]:
display(tabela["duracao_contrato"].value_counts())
display(tabela["duracao_contrato"].value_counts(normalize=True).map("{:.1%}".format))

duracao_contrato
Annual       20157
Quarterly    19959
Monthly       9884
Name: count, dtype: int64

duracao_contrato
Annual       40.3%
Quarterly    39.9%
Monthly      19.8%
Name: proportion, dtype: object

In [36]:
agrupamento = tabela.groupby("duracao_contrato").mean(numeric_only=True)

display(agrupamento)

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
duracao_contrato,,,,,,,,
Annual,38.783500,31.416452,15.909858,3.277521,12.533760,650.938395,14.232078,0.464107
Monthly,41.428470,30.677964,15.577600,4.923917,15.078814,547.508921,15.392655,1.000000
Quarterly,38.832657,31.521746,15.842277,3.255925,12.479032,654.107781,14.364247,0.458690

In [37]:
# Todos os clientes do contrato mensal cancelaram

In [ ]:
# Passo 5: Analise a causa do cancelamento dos clientes